base: &base
    filepath: '~/magikarp/core_insure/cache'
data:
    dbname: 'postgres'
    host: 'localhost'
    port: 5432
celery:
    broker_url: amqp://localhost
assessor:
    <<: *base
    model: linear_regression
    linear_regression:
        output_size: 1
        lr: 0.001
        momentum: 0.01
        epochs: 500