base: &base
    filepath: '.'
data:
    dbname: 'postgres'
    host: 'localhost'
    port: 5432
celery:
    broker_url: amqp://localhost
assessor:
    <<: *base
    model: linear_regression
    linear_regression:
        output_size: 1
        lr: 1e-5
        momentum: 0
        epochs: 500
    simple_nn:
        output_size: 1
        lr: 1e-5
        epochs: 500
        hidden_size: 50