base: &base
    filepath: '.'
assessor:
    <<: *base
    model: linear_regression
    linear_regression:
        output_size: 1
        lr: 0.01
        momentum: 0.001
        epochs: 500
    simple_nn:
        output_size: 1
        lr: 0.001
        epochs: 500
        hidden_size: 50